spring:
  application:
    name: smart-campus-backend

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://smart_campus:campus123@cluster0.fjz2qj0.mongodb.net/?appName=Cluster0}
      database: smart-campus

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: INFO
