spring:
  application:
    name: smart-campus-backend

  datasource:
    url: jdbc:mysql://localhost:3306/smart_campus_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root           # Change to your MySQL Workbench username
    password: 1234          # Change to your MySQL Workbench password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update       # Creates/updates tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

google:
  oauth:
    client-id: YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com

logging:
  level:
    root: INFO
    org.springframework.security: INFO
